apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:   
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v1.3.0  
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 400m
        memory: 600Mi        
    command:
    - /busybox/sh
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker  
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: artifactory-ismsab-dev
          items:
            - key: .dockerconfigjson
              path: config.json         
  securityContext:
    runAsUser: 0
    fsGroup: 0
